---
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  EnvironmentName:
    Description: select the environment type
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

Conditions:
  CreateProdResources: !Equals [!Ref EnvironmentName, prod]

Mappings:
  RegionImage:
    us-east-1:
      imageid: ami-05fa00d4c63e32376
    us-east-2:
      imageid: ami-0568773882d492fc8
    us-west-2:
      imageid: ami-0c2ab3b8efb09f272

  EnvironmentMap:
    dev:
      instanceType: t2.nano
    prod:
      instanceType: t2.small
Resources:
  MountPoint:
    Type: AWS::EC2::VolumeAttachment
    Condition: CreateProdResources
    Properties:
      Device: /dev/sdh     # required
      InstanceId: !Ref  MyInstance    # required
      VolumeId: !Ref  NewVolume    # required
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [RegionImage, !Ref AWS::Region, imageid]
      InstanceType: !FindInMap
        - EnvironmentMap
        - !Ref EnvironmentName
        - instanceType
  NewVolume:
    Type: AWS::EC2::Volume
    Condition: CreateProdResources
    Properties:
      AvailabilityZone: !GetAtt MyInstance.AvailabilityZone
      Size: 1
